/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package avro;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class OtpMessage extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -4482244918868194719L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"OtpMessage\",\"namespace\":\"avro\",\"fields\":[{\"name\":\"otp\",\"type\":\"string\"},{\"name\":\"failedAttempts\",\"type\":\"int\"},{\"name\":\"purpose\",\"type\":\"string\"},{\"name\":\"email\",\"type\":\"string\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<OtpMessage> ENCODER =
      new BinaryMessageEncoder<OtpMessage>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<OtpMessage> DECODER =
      new BinaryMessageDecoder<OtpMessage>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<OtpMessage> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<OtpMessage> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<OtpMessage> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<OtpMessage>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this OtpMessage to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a OtpMessage from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a OtpMessage instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static OtpMessage fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

   private java.lang.CharSequence otp;
   private int failedAttempts;
   private java.lang.CharSequence purpose;
   private java.lang.CharSequence email;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public OtpMessage() {}

  /**
   * All-args constructor.
   * @param otp The new value for otp
   * @param failedAttempts The new value for failedAttempts
   * @param purpose The new value for purpose
   * @param email The new value for email
   */
  public OtpMessage(java.lang.CharSequence otp, java.lang.Integer failedAttempts, java.lang.CharSequence purpose, java.lang.CharSequence email) {
    this.otp = otp;
    this.failedAttempts = failedAttempts;
    this.purpose = purpose;
    this.email = email;
  }

  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return otp;
    case 1: return failedAttempts;
    case 2: return purpose;
    case 3: return email;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: otp = (java.lang.CharSequence)value$; break;
    case 1: failedAttempts = (java.lang.Integer)value$; break;
    case 2: purpose = (java.lang.CharSequence)value$; break;
    case 3: email = (java.lang.CharSequence)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'otp' field.
   * @return The value of the 'otp' field.
   */
  public java.lang.CharSequence getOtp() {
    return otp;
  }


  /**
   * Sets the value of the 'otp' field.
   * @param value the value to set.
   */
  public void setOtp(java.lang.CharSequence value) {
    this.otp = value;
  }

  /**
   * Gets the value of the 'failedAttempts' field.
   * @return The value of the 'failedAttempts' field.
   */
  public int getFailedAttempts() {
    return failedAttempts;
  }


  /**
   * Sets the value of the 'failedAttempts' field.
   * @param value the value to set.
   */
  public void setFailedAttempts(int value) {
    this.failedAttempts = value;
  }

  /**
   * Gets the value of the 'purpose' field.
   * @return The value of the 'purpose' field.
   */
  public java.lang.CharSequence getPurpose() {
    return purpose;
  }


  /**
   * Sets the value of the 'purpose' field.
   * @param value the value to set.
   */
  public void setPurpose(java.lang.CharSequence value) {
    this.purpose = value;
  }

  /**
   * Gets the value of the 'email' field.
   * @return The value of the 'email' field.
   */
  public java.lang.CharSequence getEmail() {
    return email;
  }


  /**
   * Sets the value of the 'email' field.
   * @param value the value to set.
   */
  public void setEmail(java.lang.CharSequence value) {
    this.email = value;
  }

  /**
   * Creates a new OtpMessage RecordBuilder.
   * @return A new OtpMessage RecordBuilder
   */
  public static avro.OtpMessage.Builder newBuilder() {
    return new avro.OtpMessage.Builder();
  }

  /**
   * Creates a new OtpMessage RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new OtpMessage RecordBuilder
   */
  public static avro.OtpMessage.Builder newBuilder(avro.OtpMessage.Builder other) {
    if (other == null) {
      return new avro.OtpMessage.Builder();
    } else {
      return new avro.OtpMessage.Builder(other);
    }
  }

  /**
   * Creates a new OtpMessage RecordBuilder by copying an existing OtpMessage instance.
   * @param other The existing instance to copy.
   * @return A new OtpMessage RecordBuilder
   */
  public static avro.OtpMessage.Builder newBuilder(avro.OtpMessage other) {
    if (other == null) {
      return new avro.OtpMessage.Builder();
    } else {
      return new avro.OtpMessage.Builder(other);
    }
  }

  /**
   * RecordBuilder for OtpMessage instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<OtpMessage>
    implements org.apache.avro.data.RecordBuilder<OtpMessage> {

    private java.lang.CharSequence otp;
    private int failedAttempts;
    private java.lang.CharSequence purpose;
    private java.lang.CharSequence email;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(avro.OtpMessage.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.otp)) {
        this.otp = data().deepCopy(fields()[0].schema(), other.otp);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.failedAttempts)) {
        this.failedAttempts = data().deepCopy(fields()[1].schema(), other.failedAttempts);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.purpose)) {
        this.purpose = data().deepCopy(fields()[2].schema(), other.purpose);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
      if (isValidValue(fields()[3], other.email)) {
        this.email = data().deepCopy(fields()[3].schema(), other.email);
        fieldSetFlags()[3] = other.fieldSetFlags()[3];
      }
    }

    /**
     * Creates a Builder by copying an existing OtpMessage instance
     * @param other The existing instance to copy.
     */
    private Builder(avro.OtpMessage other) {
      super(SCHEMA$);
      if (isValidValue(fields()[0], other.otp)) {
        this.otp = data().deepCopy(fields()[0].schema(), other.otp);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.failedAttempts)) {
        this.failedAttempts = data().deepCopy(fields()[1].schema(), other.failedAttempts);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.purpose)) {
        this.purpose = data().deepCopy(fields()[2].schema(), other.purpose);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.email)) {
        this.email = data().deepCopy(fields()[3].schema(), other.email);
        fieldSetFlags()[3] = true;
      }
    }

    /**
      * Gets the value of the 'otp' field.
      * @return The value.
      */
    public java.lang.CharSequence getOtp() {
      return otp;
    }


    /**
      * Sets the value of the 'otp' field.
      * @param value The value of 'otp'.
      * @return This builder.
      */
    public avro.OtpMessage.Builder setOtp(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.otp = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'otp' field has been set.
      * @return True if the 'otp' field has been set, false otherwise.
      */
    public boolean hasOtp() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'otp' field.
      * @return This builder.
      */
    public avro.OtpMessage.Builder clearOtp() {
      otp = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'failedAttempts' field.
      * @return The value.
      */
    public int getFailedAttempts() {
      return failedAttempts;
    }


    /**
      * Sets the value of the 'failedAttempts' field.
      * @param value The value of 'failedAttempts'.
      * @return This builder.
      */
    public avro.OtpMessage.Builder setFailedAttempts(int value) {
      validate(fields()[1], value);
      this.failedAttempts = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'failedAttempts' field has been set.
      * @return True if the 'failedAttempts' field has been set, false otherwise.
      */
    public boolean hasFailedAttempts() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'failedAttempts' field.
      * @return This builder.
      */
    public avro.OtpMessage.Builder clearFailedAttempts() {
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'purpose' field.
      * @return The value.
      */
    public java.lang.CharSequence getPurpose() {
      return purpose;
    }


    /**
      * Sets the value of the 'purpose' field.
      * @param value The value of 'purpose'.
      * @return This builder.
      */
    public avro.OtpMessage.Builder setPurpose(java.lang.CharSequence value) {
      validate(fields()[2], value);
      this.purpose = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'purpose' field has been set.
      * @return True if the 'purpose' field has been set, false otherwise.
      */
    public boolean hasPurpose() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'purpose' field.
      * @return This builder.
      */
    public avro.OtpMessage.Builder clearPurpose() {
      purpose = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'email' field.
      * @return The value.
      */
    public java.lang.CharSequence getEmail() {
      return email;
    }


    /**
      * Sets the value of the 'email' field.
      * @param value The value of 'email'.
      * @return This builder.
      */
    public avro.OtpMessage.Builder setEmail(java.lang.CharSequence value) {
      validate(fields()[3], value);
      this.email = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'email' field has been set.
      * @return True if the 'email' field has been set, false otherwise.
      */
    public boolean hasEmail() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'email' field.
      * @return This builder.
      */
    public avro.OtpMessage.Builder clearEmail() {
      email = null;
      fieldSetFlags()[3] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public OtpMessage build() {
      try {
        OtpMessage record = new OtpMessage();
        record.otp = fieldSetFlags()[0] ? this.otp : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.failedAttempts = fieldSetFlags()[1] ? this.failedAttempts : (java.lang.Integer) defaultValue(fields()[1]);
        record.purpose = fieldSetFlags()[2] ? this.purpose : (java.lang.CharSequence) defaultValue(fields()[2]);
        record.email = fieldSetFlags()[3] ? this.email : (java.lang.CharSequence) defaultValue(fields()[3]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<OtpMessage>
    WRITER$ = (org.apache.avro.io.DatumWriter<OtpMessage>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<OtpMessage>
    READER$ = (org.apache.avro.io.DatumReader<OtpMessage>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeString(this.otp);

    out.writeInt(this.failedAttempts);

    out.writeString(this.purpose);

    out.writeString(this.email);

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.otp = in.readString(this.otp instanceof Utf8 ? (Utf8)this.otp : null);

      this.failedAttempts = in.readInt();

      this.purpose = in.readString(this.purpose instanceof Utf8 ? (Utf8)this.purpose : null);

      this.email = in.readString(this.email instanceof Utf8 ? (Utf8)this.email : null);

    } else {
      for (int i = 0; i < 4; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.otp = in.readString(this.otp instanceof Utf8 ? (Utf8)this.otp : null);
          break;

        case 1:
          this.failedAttempts = in.readInt();
          break;

        case 2:
          this.purpose = in.readString(this.purpose instanceof Utf8 ? (Utf8)this.purpose : null);
          break;

        case 3:
          this.email = in.readString(this.email instanceof Utf8 ? (Utf8)this.email : null);
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










