/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.osc.sessiondataservice.avro;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class SessionAvro extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -4948973394028936220L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"SessionAvro\",\"namespace\":\"com.osc.sessiondataservice.avro\",\"fields\":[{\"name\":\"SessionStatus\",\"type\":\"boolean\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<SessionAvro> ENCODER =
      new BinaryMessageEncoder<SessionAvro>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<SessionAvro> DECODER =
      new BinaryMessageDecoder<SessionAvro>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<SessionAvro> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<SessionAvro> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<SessionAvro> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<SessionAvro>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this SessionAvro to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a SessionAvro from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a SessionAvro instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static SessionAvro fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

   private boolean SessionStatus;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public SessionAvro() {}

  /**
   * All-args constructor.
   * @param SessionStatus The new value for SessionStatus
   */
  public SessionAvro(java.lang.Boolean SessionStatus) {
    this.SessionStatus = SessionStatus;
  }

  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return SessionStatus;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: SessionStatus = (java.lang.Boolean)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'SessionStatus' field.
   * @return The value of the 'SessionStatus' field.
   */
  public boolean getSessionStatus() {
    return SessionStatus;
  }


  /**
   * Sets the value of the 'SessionStatus' field.
   * @param value the value to set.
   */
  public void setSessionStatus(boolean value) {
    this.SessionStatus = value;
  }

  /**
   * Creates a new SessionAvro RecordBuilder.
   * @return A new SessionAvro RecordBuilder
   */
  public static com.osc.sessiondataservice.avro.SessionAvro.Builder newBuilder() {
    return new com.osc.sessiondataservice.avro.SessionAvro.Builder();
  }

  /**
   * Creates a new SessionAvro RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new SessionAvro RecordBuilder
   */
  public static com.osc.sessiondataservice.avro.SessionAvro.Builder newBuilder(com.osc.sessiondataservice.avro.SessionAvro.Builder other) {
    if (other == null) {
      return new com.osc.sessiondataservice.avro.SessionAvro.Builder();
    } else {
      return new com.osc.sessiondataservice.avro.SessionAvro.Builder(other);
    }
  }

  /**
   * Creates a new SessionAvro RecordBuilder by copying an existing SessionAvro instance.
   * @param other The existing instance to copy.
   * @return A new SessionAvro RecordBuilder
   */
  public static com.osc.sessiondataservice.avro.SessionAvro.Builder newBuilder(com.osc.sessiondataservice.avro.SessionAvro other) {
    if (other == null) {
      return new com.osc.sessiondataservice.avro.SessionAvro.Builder();
    } else {
      return new com.osc.sessiondataservice.avro.SessionAvro.Builder(other);
    }
  }

  /**
   * RecordBuilder for SessionAvro instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<SessionAvro>
    implements org.apache.avro.data.RecordBuilder<SessionAvro> {

    private boolean SessionStatus;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.osc.sessiondataservice.avro.SessionAvro.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.SessionStatus)) {
        this.SessionStatus = data().deepCopy(fields()[0].schema(), other.SessionStatus);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
    }

    /**
     * Creates a Builder by copying an existing SessionAvro instance
     * @param other The existing instance to copy.
     */
    private Builder(com.osc.sessiondataservice.avro.SessionAvro other) {
      super(SCHEMA$);
      if (isValidValue(fields()[0], other.SessionStatus)) {
        this.SessionStatus = data().deepCopy(fields()[0].schema(), other.SessionStatus);
        fieldSetFlags()[0] = true;
      }
    }

    /**
      * Gets the value of the 'SessionStatus' field.
      * @return The value.
      */
    public boolean getSessionStatus() {
      return SessionStatus;
    }


    /**
      * Sets the value of the 'SessionStatus' field.
      * @param value The value of 'SessionStatus'.
      * @return This builder.
      */
    public com.osc.sessiondataservice.avro.SessionAvro.Builder setSessionStatus(boolean value) {
      validate(fields()[0], value);
      this.SessionStatus = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'SessionStatus' field has been set.
      * @return True if the 'SessionStatus' field has been set, false otherwise.
      */
    public boolean hasSessionStatus() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'SessionStatus' field.
      * @return This builder.
      */
    public com.osc.sessiondataservice.avro.SessionAvro.Builder clearSessionStatus() {
      fieldSetFlags()[0] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public SessionAvro build() {
      try {
        SessionAvro record = new SessionAvro();
        record.SessionStatus = fieldSetFlags()[0] ? this.SessionStatus : (java.lang.Boolean) defaultValue(fields()[0]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<SessionAvro>
    WRITER$ = (org.apache.avro.io.DatumWriter<SessionAvro>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<SessionAvro>
    READER$ = (org.apache.avro.io.DatumReader<SessionAvro>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeBoolean(this.SessionStatus);

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.SessionStatus = in.readBoolean();

    } else {
      for (int i = 0; i < 1; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.SessionStatus = in.readBoolean();
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










