/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.osc.avro.files;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class CartProduct extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 1496589191593226833L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"CartProduct\",\"namespace\":\"com.osc.avro.files\",\"fields\":[{\"name\":\"productId\",\"type\":\"string\"},{\"name\":\"productQuantity\",\"type\":\"int\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<CartProduct> ENCODER =
      new BinaryMessageEncoder<CartProduct>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<CartProduct> DECODER =
      new BinaryMessageDecoder<CartProduct>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<CartProduct> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<CartProduct> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<CartProduct> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<CartProduct>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this CartProduct to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a CartProduct from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a CartProduct instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static CartProduct fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

   private java.lang.CharSequence productId;
   private int productQuantity;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public CartProduct() {}

  /**
   * All-args constructor.
   * @param productId The new value for productId
   * @param productQuantity The new value for productQuantity
   */
  public CartProduct(java.lang.CharSequence productId, java.lang.Integer productQuantity) {
    this.productId = productId;
    this.productQuantity = productQuantity;
  }

  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return productId;
    case 1: return productQuantity;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: productId = (java.lang.CharSequence)value$; break;
    case 1: productQuantity = (java.lang.Integer)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'productId' field.
   * @return The value of the 'productId' field.
   */
  public java.lang.CharSequence getProductId() {
    return productId;
  }


  /**
   * Sets the value of the 'productId' field.
   * @param value the value to set.
   */
  public void setProductId(java.lang.CharSequence value) {
    this.productId = value;
  }

  /**
   * Gets the value of the 'productQuantity' field.
   * @return The value of the 'productQuantity' field.
   */
  public int getProductQuantity() {
    return productQuantity;
  }


  /**
   * Sets the value of the 'productQuantity' field.
   * @param value the value to set.
   */
  public void setProductQuantity(int value) {
    this.productQuantity = value;
  }

  /**
   * Creates a new CartProduct RecordBuilder.
   * @return A new CartProduct RecordBuilder
   */
  public static com.osc.avro.files.CartProduct.Builder newBuilder() {
    return new com.osc.avro.files.CartProduct.Builder();
  }

  /**
   * Creates a new CartProduct RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new CartProduct RecordBuilder
   */
  public static com.osc.avro.files.CartProduct.Builder newBuilder(com.osc.avro.files.CartProduct.Builder other) {
    if (other == null) {
      return new com.osc.avro.files.CartProduct.Builder();
    } else {
      return new com.osc.avro.files.CartProduct.Builder(other);
    }
  }

  /**
   * Creates a new CartProduct RecordBuilder by copying an existing CartProduct instance.
   * @param other The existing instance to copy.
   * @return A new CartProduct RecordBuilder
   */
  public static com.osc.avro.files.CartProduct.Builder newBuilder(com.osc.avro.files.CartProduct other) {
    if (other == null) {
      return new com.osc.avro.files.CartProduct.Builder();
    } else {
      return new com.osc.avro.files.CartProduct.Builder(other);
    }
  }

  /**
   * RecordBuilder for CartProduct instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<CartProduct>
    implements org.apache.avro.data.RecordBuilder<CartProduct> {

    private java.lang.CharSequence productId;
    private int productQuantity;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.osc.avro.files.CartProduct.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.productId)) {
        this.productId = data().deepCopy(fields()[0].schema(), other.productId);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.productQuantity)) {
        this.productQuantity = data().deepCopy(fields()[1].schema(), other.productQuantity);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
    }

    /**
     * Creates a Builder by copying an existing CartProduct instance
     * @param other The existing instance to copy.
     */
    private Builder(com.osc.avro.files.CartProduct other) {
      super(SCHEMA$);
      if (isValidValue(fields()[0], other.productId)) {
        this.productId = data().deepCopy(fields()[0].schema(), other.productId);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.productQuantity)) {
        this.productQuantity = data().deepCopy(fields()[1].schema(), other.productQuantity);
        fieldSetFlags()[1] = true;
      }
    }

    /**
      * Gets the value of the 'productId' field.
      * @return The value.
      */
    public java.lang.CharSequence getProductId() {
      return productId;
    }


    /**
      * Sets the value of the 'productId' field.
      * @param value The value of 'productId'.
      * @return This builder.
      */
    public com.osc.avro.files.CartProduct.Builder setProductId(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.productId = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'productId' field has been set.
      * @return True if the 'productId' field has been set, false otherwise.
      */
    public boolean hasProductId() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'productId' field.
      * @return This builder.
      */
    public com.osc.avro.files.CartProduct.Builder clearProductId() {
      productId = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'productQuantity' field.
      * @return The value.
      */
    public int getProductQuantity() {
      return productQuantity;
    }


    /**
      * Sets the value of the 'productQuantity' field.
      * @param value The value of 'productQuantity'.
      * @return This builder.
      */
    public com.osc.avro.files.CartProduct.Builder setProductQuantity(int value) {
      validate(fields()[1], value);
      this.productQuantity = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'productQuantity' field has been set.
      * @return True if the 'productQuantity' field has been set, false otherwise.
      */
    public boolean hasProductQuantity() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'productQuantity' field.
      * @return This builder.
      */
    public com.osc.avro.files.CartProduct.Builder clearProductQuantity() {
      fieldSetFlags()[1] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public CartProduct build() {
      try {
        CartProduct record = new CartProduct();
        record.productId = fieldSetFlags()[0] ? this.productId : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.productQuantity = fieldSetFlags()[1] ? this.productQuantity : (java.lang.Integer) defaultValue(fields()[1]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<CartProduct>
    WRITER$ = (org.apache.avro.io.DatumWriter<CartProduct>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<CartProduct>
    READER$ = (org.apache.avro.io.DatumReader<CartProduct>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeString(this.productId);

    out.writeInt(this.productQuantity);

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.productId = in.readString(this.productId instanceof Utf8 ? (Utf8)this.productId : null);

      this.productQuantity = in.readInt();

    } else {
      for (int i = 0; i < 2; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.productId = in.readString(this.productId instanceof Utf8 ? (Utf8)this.productId : null);
          break;

        case 1:
          this.productQuantity = in.readInt();
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










