/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.osc.avro.files;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class Product extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -6598299502139804317L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"Product\",\"namespace\":\"com.osc.avro.files\",\"fields\":[{\"name\":\"categoryId\",\"type\":\"string\"},{\"name\":\"productName\",\"type\":\"string\"},{\"name\":\"productPrice\",\"type\":\"double\"},{\"name\":\"productDescription\",\"type\":\"string\"},{\"name\":\"imagePath\",\"type\":\"string\"},{\"name\":\"addedDateTime\",\"type\":\"long\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<Product> ENCODER =
      new BinaryMessageEncoder<Product>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<Product> DECODER =
      new BinaryMessageDecoder<Product>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<Product> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<Product> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<Product> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<Product>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this Product to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a Product from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a Product instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static Product fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

   private java.lang.CharSequence categoryId;
   private java.lang.CharSequence productName;
   private double productPrice;
   private java.lang.CharSequence productDescription;
   private java.lang.CharSequence imagePath;
   private long addedDateTime;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public Product() {}

  /**
   * All-args constructor.
   * @param categoryId The new value for categoryId
   * @param productName The new value for productName
   * @param productPrice The new value for productPrice
   * @param productDescription The new value for productDescription
   * @param imagePath The new value for imagePath
   * @param addedDateTime The new value for addedDateTime
   */
  public Product(java.lang.CharSequence categoryId, java.lang.CharSequence productName, java.lang.Double productPrice, java.lang.CharSequence productDescription, java.lang.CharSequence imagePath, java.lang.Long addedDateTime) {
    this.categoryId = categoryId;
    this.productName = productName;
    this.productPrice = productPrice;
    this.productDescription = productDescription;
    this.imagePath = imagePath;
    this.addedDateTime = addedDateTime;
  }

  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return categoryId;
    case 1: return productName;
    case 2: return productPrice;
    case 3: return productDescription;
    case 4: return imagePath;
    case 5: return addedDateTime;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: categoryId = (java.lang.CharSequence)value$; break;
    case 1: productName = (java.lang.CharSequence)value$; break;
    case 2: productPrice = (java.lang.Double)value$; break;
    case 3: productDescription = (java.lang.CharSequence)value$; break;
    case 4: imagePath = (java.lang.CharSequence)value$; break;
    case 5: addedDateTime = (java.lang.Long)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'categoryId' field.
   * @return The value of the 'categoryId' field.
   */
  public java.lang.CharSequence getCategoryId() {
    return categoryId;
  }


  /**
   * Sets the value of the 'categoryId' field.
   * @param value the value to set.
   */
  public void setCategoryId(java.lang.CharSequence value) {
    this.categoryId = value;
  }

  /**
   * Gets the value of the 'productName' field.
   * @return The value of the 'productName' field.
   */
  public java.lang.CharSequence getProductName() {
    return productName;
  }


  /**
   * Sets the value of the 'productName' field.
   * @param value the value to set.
   */
  public void setProductName(java.lang.CharSequence value) {
    this.productName = value;
  }

  /**
   * Gets the value of the 'productPrice' field.
   * @return The value of the 'productPrice' field.
   */
  public double getProductPrice() {
    return productPrice;
  }


  /**
   * Sets the value of the 'productPrice' field.
   * @param value the value to set.
   */
  public void setProductPrice(double value) {
    this.productPrice = value;
  }

  /**
   * Gets the value of the 'productDescription' field.
   * @return The value of the 'productDescription' field.
   */
  public java.lang.CharSequence getProductDescription() {
    return productDescription;
  }


  /**
   * Sets the value of the 'productDescription' field.
   * @param value the value to set.
   */
  public void setProductDescription(java.lang.CharSequence value) {
    this.productDescription = value;
  }

  /**
   * Gets the value of the 'imagePath' field.
   * @return The value of the 'imagePath' field.
   */
  public java.lang.CharSequence getImagePath() {
    return imagePath;
  }


  /**
   * Sets the value of the 'imagePath' field.
   * @param value the value to set.
   */
  public void setImagePath(java.lang.CharSequence value) {
    this.imagePath = value;
  }

  /**
   * Gets the value of the 'addedDateTime' field.
   * @return The value of the 'addedDateTime' field.
   */
  public long getAddedDateTime() {
    return addedDateTime;
  }


  /**
   * Sets the value of the 'addedDateTime' field.
   * @param value the value to set.
   */
  public void setAddedDateTime(long value) {
    this.addedDateTime = value;
  }

  /**
   * Creates a new Product RecordBuilder.
   * @return A new Product RecordBuilder
   */
  public static com.osc.avro.files.Product.Builder newBuilder() {
    return new com.osc.avro.files.Product.Builder();
  }

  /**
   * Creates a new Product RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new Product RecordBuilder
   */
  public static com.osc.avro.files.Product.Builder newBuilder(com.osc.avro.files.Product.Builder other) {
    if (other == null) {
      return new com.osc.avro.files.Product.Builder();
    } else {
      return new com.osc.avro.files.Product.Builder(other);
    }
  }

  /**
   * Creates a new Product RecordBuilder by copying an existing Product instance.
   * @param other The existing instance to copy.
   * @return A new Product RecordBuilder
   */
  public static com.osc.avro.files.Product.Builder newBuilder(com.osc.avro.files.Product other) {
    if (other == null) {
      return new com.osc.avro.files.Product.Builder();
    } else {
      return new com.osc.avro.files.Product.Builder(other);
    }
  }

  /**
   * RecordBuilder for Product instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<Product>
    implements org.apache.avro.data.RecordBuilder<Product> {

    private java.lang.CharSequence categoryId;
    private java.lang.CharSequence productName;
    private double productPrice;
    private java.lang.CharSequence productDescription;
    private java.lang.CharSequence imagePath;
    private long addedDateTime;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.osc.avro.files.Product.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.categoryId)) {
        this.categoryId = data().deepCopy(fields()[0].schema(), other.categoryId);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.productName)) {
        this.productName = data().deepCopy(fields()[1].schema(), other.productName);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.productPrice)) {
        this.productPrice = data().deepCopy(fields()[2].schema(), other.productPrice);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
      if (isValidValue(fields()[3], other.productDescription)) {
        this.productDescription = data().deepCopy(fields()[3].schema(), other.productDescription);
        fieldSetFlags()[3] = other.fieldSetFlags()[3];
      }
      if (isValidValue(fields()[4], other.imagePath)) {
        this.imagePath = data().deepCopy(fields()[4].schema(), other.imagePath);
        fieldSetFlags()[4] = other.fieldSetFlags()[4];
      }
      if (isValidValue(fields()[5], other.addedDateTime)) {
        this.addedDateTime = data().deepCopy(fields()[5].schema(), other.addedDateTime);
        fieldSetFlags()[5] = other.fieldSetFlags()[5];
      }
    }

    /**
     * Creates a Builder by copying an existing Product instance
     * @param other The existing instance to copy.
     */
    private Builder(com.osc.avro.files.Product other) {
      super(SCHEMA$);
      if (isValidValue(fields()[0], other.categoryId)) {
        this.categoryId = data().deepCopy(fields()[0].schema(), other.categoryId);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.productName)) {
        this.productName = data().deepCopy(fields()[1].schema(), other.productName);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.productPrice)) {
        this.productPrice = data().deepCopy(fields()[2].schema(), other.productPrice);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.productDescription)) {
        this.productDescription = data().deepCopy(fields()[3].schema(), other.productDescription);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.imagePath)) {
        this.imagePath = data().deepCopy(fields()[4].schema(), other.imagePath);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.addedDateTime)) {
        this.addedDateTime = data().deepCopy(fields()[5].schema(), other.addedDateTime);
        fieldSetFlags()[5] = true;
      }
    }

    /**
      * Gets the value of the 'categoryId' field.
      * @return The value.
      */
    public java.lang.CharSequence getCategoryId() {
      return categoryId;
    }


    /**
      * Sets the value of the 'categoryId' field.
      * @param value The value of 'categoryId'.
      * @return This builder.
      */
    public com.osc.avro.files.Product.Builder setCategoryId(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.categoryId = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'categoryId' field has been set.
      * @return True if the 'categoryId' field has been set, false otherwise.
      */
    public boolean hasCategoryId() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'categoryId' field.
      * @return This builder.
      */
    public com.osc.avro.files.Product.Builder clearCategoryId() {
      categoryId = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'productName' field.
      * @return The value.
      */
    public java.lang.CharSequence getProductName() {
      return productName;
    }


    /**
      * Sets the value of the 'productName' field.
      * @param value The value of 'productName'.
      * @return This builder.
      */
    public com.osc.avro.files.Product.Builder setProductName(java.lang.CharSequence value) {
      validate(fields()[1], value);
      this.productName = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'productName' field has been set.
      * @return True if the 'productName' field has been set, false otherwise.
      */
    public boolean hasProductName() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'productName' field.
      * @return This builder.
      */
    public com.osc.avro.files.Product.Builder clearProductName() {
      productName = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'productPrice' field.
      * @return The value.
      */
    public double getProductPrice() {
      return productPrice;
    }


    /**
      * Sets the value of the 'productPrice' field.
      * @param value The value of 'productPrice'.
      * @return This builder.
      */
    public com.osc.avro.files.Product.Builder setProductPrice(double value) {
      validate(fields()[2], value);
      this.productPrice = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'productPrice' field has been set.
      * @return True if the 'productPrice' field has been set, false otherwise.
      */
    public boolean hasProductPrice() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'productPrice' field.
      * @return This builder.
      */
    public com.osc.avro.files.Product.Builder clearProductPrice() {
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'productDescription' field.
      * @return The value.
      */
    public java.lang.CharSequence getProductDescription() {
      return productDescription;
    }


    /**
      * Sets the value of the 'productDescription' field.
      * @param value The value of 'productDescription'.
      * @return This builder.
      */
    public com.osc.avro.files.Product.Builder setProductDescription(java.lang.CharSequence value) {
      validate(fields()[3], value);
      this.productDescription = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'productDescription' field has been set.
      * @return True if the 'productDescription' field has been set, false otherwise.
      */
    public boolean hasProductDescription() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'productDescription' field.
      * @return This builder.
      */
    public com.osc.avro.files.Product.Builder clearProductDescription() {
      productDescription = null;
      fieldSetFlags()[3] = false;
      return this;
    }

    /**
      * Gets the value of the 'imagePath' field.
      * @return The value.
      */
    public java.lang.CharSequence getImagePath() {
      return imagePath;
    }


    /**
      * Sets the value of the 'imagePath' field.
      * @param value The value of 'imagePath'.
      * @return This builder.
      */
    public com.osc.avro.files.Product.Builder setImagePath(java.lang.CharSequence value) {
      validate(fields()[4], value);
      this.imagePath = value;
      fieldSetFlags()[4] = true;
      return this;
    }

    /**
      * Checks whether the 'imagePath' field has been set.
      * @return True if the 'imagePath' field has been set, false otherwise.
      */
    public boolean hasImagePath() {
      return fieldSetFlags()[4];
    }


    /**
      * Clears the value of the 'imagePath' field.
      * @return This builder.
      */
    public com.osc.avro.files.Product.Builder clearImagePath() {
      imagePath = null;
      fieldSetFlags()[4] = false;
      return this;
    }

    /**
      * Gets the value of the 'addedDateTime' field.
      * @return The value.
      */
    public long getAddedDateTime() {
      return addedDateTime;
    }


    /**
      * Sets the value of the 'addedDateTime' field.
      * @param value The value of 'addedDateTime'.
      * @return This builder.
      */
    public com.osc.avro.files.Product.Builder setAddedDateTime(long value) {
      validate(fields()[5], value);
      this.addedDateTime = value;
      fieldSetFlags()[5] = true;
      return this;
    }

    /**
      * Checks whether the 'addedDateTime' field has been set.
      * @return True if the 'addedDateTime' field has been set, false otherwise.
      */
    public boolean hasAddedDateTime() {
      return fieldSetFlags()[5];
    }


    /**
      * Clears the value of the 'addedDateTime' field.
      * @return This builder.
      */
    public com.osc.avro.files.Product.Builder clearAddedDateTime() {
      fieldSetFlags()[5] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public Product build() {
      try {
        Product record = new Product();
        record.categoryId = fieldSetFlags()[0] ? this.categoryId : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.productName = fieldSetFlags()[1] ? this.productName : (java.lang.CharSequence) defaultValue(fields()[1]);
        record.productPrice = fieldSetFlags()[2] ? this.productPrice : (java.lang.Double) defaultValue(fields()[2]);
        record.productDescription = fieldSetFlags()[3] ? this.productDescription : (java.lang.CharSequence) defaultValue(fields()[3]);
        record.imagePath = fieldSetFlags()[4] ? this.imagePath : (java.lang.CharSequence) defaultValue(fields()[4]);
        record.addedDateTime = fieldSetFlags()[5] ? this.addedDateTime : (java.lang.Long) defaultValue(fields()[5]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<Product>
    WRITER$ = (org.apache.avro.io.DatumWriter<Product>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<Product>
    READER$ = (org.apache.avro.io.DatumReader<Product>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeString(this.categoryId);

    out.writeString(this.productName);

    out.writeDouble(this.productPrice);

    out.writeString(this.productDescription);

    out.writeString(this.imagePath);

    out.writeLong(this.addedDateTime);

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.categoryId = in.readString(this.categoryId instanceof Utf8 ? (Utf8)this.categoryId : null);

      this.productName = in.readString(this.productName instanceof Utf8 ? (Utf8)this.productName : null);

      this.productPrice = in.readDouble();

      this.productDescription = in.readString(this.productDescription instanceof Utf8 ? (Utf8)this.productDescription : null);

      this.imagePath = in.readString(this.imagePath instanceof Utf8 ? (Utf8)this.imagePath : null);

      this.addedDateTime = in.readLong();

    } else {
      for (int i = 0; i < 6; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.categoryId = in.readString(this.categoryId instanceof Utf8 ? (Utf8)this.categoryId : null);
          break;

        case 1:
          this.productName = in.readString(this.productName instanceof Utf8 ? (Utf8)this.productName : null);
          break;

        case 2:
          this.productPrice = in.readDouble();
          break;

        case 3:
          this.productDescription = in.readString(this.productDescription instanceof Utf8 ? (Utf8)this.productDescription : null);
          break;

        case 4:
          this.imagePath = in.readString(this.imagePath instanceof Utf8 ? (Utf8)this.imagePath : null);
          break;

        case 5:
          this.addedDateTime = in.readLong();
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










